inp = ['61',
       'Ana Breanna Rahul Miranda Glenn Rohit Tanya Raju Michele Angel Sejal Kinjal Francisco Linda Mahesh Lauren Colleen Austin Tejas Deanna Susan Lisa Girish Anushree Sarah Patrick Samantha Dana Rajni Babita Nikita Brad Inder Cody Tiffany Neel Mary Misty Sumit Chandra Raj Pranav Pamela Andrea Jason Valerie Meredith Rajas Erica James Daniel Julie Nikhil Angela Christopher Priya Kristen Anubhav Bryan Philip Nishi',
       '18 21', '11 14', '1 14', '5 18', '20 21', '6 19', '15 20', '5 18', '6 8', '3 21', '20 21', '8 14', '3 5',
       '9 21', '17 19', '8 10', '6 7', '4 10', '1 9', '9 16', '9 16', '3 9', '19 21', '3 16', '11 14', '3 7', '15 18',
       '5 17', '9 14', '20 21', '16 20', '13 18', '15 16', '11 20', '18 20', '17 21', '17 21', '18 20', '1 9', '19 21',
       '15 20', '18 20', '20 21', '16 20', '14 21', '18 21', '12 14', '11 16', '6 11', '10 18', '4 12', '19 21', '8 16',
       '16 17', '5 19', '2 20', '7 21', '15 17', '10 14', '18 21', '14 17']

output = [['3', '1 7 1 Bradley', '7 9 3 Bradley Erika Melanie', '9 10 2 Bradley Melanie'],
          ['5', '10 11 2 Ariel David', '11 12 3 Ariel Christine David', '12 14 3 Ariel David Dimple',
           '14 15 3 David Dimple George', '15 16 2 Dimple George'], ['2', '15 16 1 Janet', '16 18 0 ', '18 20 1 Cody'],
          ['3', '3 10 1 Miss', '10 11 2 Miss Pavitra', '11 13 3 Kelli Miss Pavitra', '13 18 2 Kelli Pavitra',
           '18 19 1 Kelli'],
          ['8', '1 2 1 Shyam', '2 8 2 Mary Shyam', '8 9 3 Kumar Mary Shyam', '9 11 4 Chhavi Kumar Mary Shyam',
           '11 12 3 Girish Shyam Vaishnavi', '12 17 1 Girish', '17 18 3 Allison Girish James', '18 21 2 Allison James'],
          ['8', '4 5 1 Nishi', '5 11 5 Aaron Aniket Charles Farida Nishi', '11 12 5 Aaron Charles Dustin Farida Nishi',
           '12 14 5 Aaron Dustin Farida Nishi Sonia', '14 18 2 Aaron Dustin', '18 20 1 Aaron', '20 21 1 Erin'],
          ['4', '5 16 1 Rohit', '16 18 2 Rohit Yukta', '18 20 3 Ashwini Rohit Yukta', '20 21 2 Rohit Siya'],
          ['4', '6 11 1 Priya', '11 13 2 Bobby Priya', '13 19 0 ', '19 20 1 Penny', '20 21 2 Penny Shilpa'],
          ['13', '1 3 1 Alia', '3 4 2 Alia Mary', '4 6 4 Alia Annette Linda Mary',
           '6 7 6 Alia Annette Linda Marcus Mary Sakshi',
           '7 8 8 Alia Annette Kayla Lauren Linda Marcus Mary Sakshi',
           '8 9 7 Alia Annette Kayla Lauren Linda Marcus Sakshi',
           '9 10 8 Alia Annette Kayla Kumar Lauren Linda Marcus Sakshi',
           '10 12 9 Alia Anirudh Annette Kayla Kumar Lauren Linda Marcus Sakshi',
           '12 13 8 Alia Anirudh Annette Kayla Kumar Linda Marcus Sakshi',
           '13 14 9 Alia Anirudh Annette Kayla Kumar Linda Marcus Ritu Sakshi',
           '14 15 8 Anirudh Annette Kayla Kumar Linda Marcus Ritu Sakshi',
           '15 16 7 Anirudh Annette Kumar Linda Marcus Ritu Sakshi', '16 17 4 Anirudh Annette Linda Ritu',
           '17 18 2 Annette Ritu', '18 19 1 Annette', '19 20 2 Annette Carrie', '20 21 2 Annette Connie'],
          ['9', '2 4 1 Sumit', '4 5 2 Dimple Sumit', '5 7 3 Dimple Siddharth Sumit',
           '7 9 5 Dimple Martin Siddharth Sumit Vaishnavi', '9 13 6 Dimple Martin Nicole Siddharth Sumit Vaishnavi',
           '13 18 4 Dimple Nicole Siddharth Sumit', '18 19 5 Dimple Dinesh Nicole Siddharth Sumit',
           '19 20 5 Anirudh Dinesh Nicole Siddharth Sumit', '20 21 6 Anirudh Dinesh Jake Nicole Siddharth Sumit'],
          ['8', '3 4 1 Dinesh', '4 6 3 Bryan Dinesh Khushi', '6 9 2 Bryan Khushi',
           '9 11 5 Bryan Dennis Khushi Miranda Siddharth', '11 14 4 Bryan Khushi Miranda Siddharth',
           '14 15 5 Bryan Khushi Miguel Miranda Siddharth', '15 16 3 Bryan Miranda Siddharth', '16 18 1 Siddharth',
           '18 19 2 Muskan Siddharth', '19 20 1 Muskan'],
          ['15', '2 3 1 Farida', '3 4 2 Farida Tom', '4 6 3 Farida Shardul Tom', '6 7 2 Shardul Tom',
           '7 10 7 Aashna Alan Ashley Kayla Shardul Shreya Tom',
           '10 11 8 Aashna Alan Ashley Kartik Kayla Shardul Shreya Tom',
           '11 13 8 Aashna Alan Ashley Connie Kartik Kayla Shardul Shreya',
           '13 15 5 Connie Kartik Kayla Shardul Shreya',
           '15 16 4 Connie Kartik Kayla Shreya', '16 17 5 Angel Connie Kartik Shreya Tim',
           '17 18 4 Angel Kartik Shreya Tim',
           '18 19 4 Angel Raven Shreya Tim', '19 20 5 Andrew Angel Raven Shreya Tim',
           '20 21 4 Andrew Angel Bianca Raven'],
          ['12', '1 2 1 Alia', '2 3 2 Alia Claire', '3 4 3 Alia Claire Randy',
           '4 5 6 Aaron Alia Claire Daniel Laura Randy',
           '5 7 8 Aaron Alia Anubhav Claire Daniel Laura Randy Vikas',
           '7 8 7 Aaron Alia Anubhav Claire Laura Randy Vikas',
           '8 9 6 Aaron Alia Claire Laura Randy Vikas', '9 10 7 Aaron Alia Bailey Claire Laura Randy Vikas',
           '10 13 8 Aaron Alia Bailey Claire Laura Randy Sid Vikas',
           '13 14 8 Alia Bailey Claire Laura Randy Seema Sid Vikas',
           '14 16 5 Bailey Claire Seema Sid Vikas', '16 17 4 Bailey Claire Seema Vikas', '17 18 3 Bailey Claire Seema',
           '18 20 3 Bailey Claire Jacob', '20 21 1 Claire'],
          ['15', '1 3 1 George', '3 4 2 Anamika George', '4 6 3 Anamika George Shardul',
           '6 7 4 Anamika Anirudh George Shardul',
           '7 8 5 Anamika Anirudh George Shardul Vedant', '8 9 7 Anamika Anirudh Brittany George Neha Shardul Vedant',
           '9 10 7 Anamika Anirudh Brittany Neha Rutuja Shardul Vedant',
           '10 11 7 Akanksha Anamika Anirudh Neha Rutuja Shardul Vedant',
           '11 12 8 Akanksha Anamika Anirudh Jared Neha Rutuja Shardul Vedant',
           '12 13 6 Akanksha Anamika Anirudh Jared Neha Vedant',
           '13 14 7 Akanksha Anamika Anirudh Jared Kevin Neha Vedant',
           '14 15 6 Akanksha Anamika Jared Kevin Neha Vedant', '15 16 6 Akanksha Anamika Jared Kevin Roger Vedant',
           '16 17 4 Akanksha Anamika Kevin Vedant', '17 19 6 Akanksha Anamika Kevin Sheri Vedant Vicki',
           '19 20 5 Anamika Kevin Sheri Vedant Vicki', '20 21 2 Anamika Anuja'],
          ['12', '1 2 1 Anubhav', '2 5 2 Anubhav Niraj', '5 7 3 Anubhav Mukesh Niraj', '7 9 2 Anubhav Niraj',
           '9 10 3 Anubhav Carl Niraj', '10 12 3 Anubhav Leonard Niraj', '12 13 4 Anubhav Leonard Niraj Paras',
           '13 15 6 Anubhav Brittany Jeffrey Leonard Niraj Paras', '15 16 5 Anubhav Brittany Leonard Niraj Paras',
           '16 17 8 Aditi Anubhav Ayushi Brittany Leonard Niraj Paras Raj',
           '17 19 7 Anubhav Ayushi Brittany Dinesh Niraj Paras Raj', '19 20 6 Anubhav Ayushi Brittany Dinesh Paras Raj',
           '20 21 4 Anubhav Ayushi Brittany Raj'],
          ['9', '4 5 1 Kevin', '5 11 3 Jeffery Kevin Leslie', '11 12 4 Jeffery Kevin Kritika Leslie',
           '12 14 5 Aastha Jeffery Kevin Kritika Leslie', '14 15 6 Aastha Jeffery Kevin Kritika Leslie Mukesh',
           '15 16 7 Aastha Jeffery Kevin Kritika Leslie Mukesh Sharon', '16 17 5 Jeffery Kevin Kritika Mukesh Sharon',
           '17 19 3 Jeffery Kritika Sharon', '19 20 3 Jeffery Phillip Sharon', '20 21 1 Deepika'],
          ['11', '2 3 1 Claire', '3 5 2 Claire Swati', '5 8 0 ', '8 9 1 Isabella', '9 11 2 Debbie Isabella',
           '11 13 3 Debbie Isabella Yogesh', '13 15 4 Debbie Isabella Kumar Yogesh',
           '15 16 5 Debbie Isabella Kumar Lavanya Yogesh', '16 18 4 Debbie Isabella Kumar Yogesh',
           '18 19 7 Chandra Debbie Isabella Kathryn Kumar Steven Yogesh',
           '19 20 6 Debbie Isabella Kathryn Kumar Kunal Yogesh',
           '20 21 4 Isabella Kathryn Kunal Yogesh'],
          ['8', '5 6 3 Abhinav Babita Keith', '6 7 2 Babita Keith', '7 8 3 Babita Keith Stephanie',
           '8 10 3 Ishika Keith Stephanie', '10 11 4 David Ishika Keith Stephanie',
           '11 12 5 David Ishika Keith Olivia Stephanie', '12 14 4 David Ishika Keith Stephanie',
           '14 17 3 Ishika Keith Stephanie', '17 20 2 Keith Melinda'],
          ['13', '7 8 2 Aashna Melody', '8 10 3 Aashna Abhishek Melody', '10 11 2 Aashna Sara',
           '11 12 5 Aashna Annette Francisco Larry Sara', '12 13 4 Aashna Annette Larry Sara',
           '13 14 6 Aashna Annette Dimple Larry Marcus Sara', '14 15 5 Aashna Annette Larry Marcus Sara',
           '15 16 7 Aashna Annette Jaclyn Larry Marcus Raju Sara', '16 17 4 Aashna Jaclyn Marcus Sara',
           '17 18 3 Jaclyn Marcus Sara', '18 19 2 Alexandra Jaclyn', '19 20 2 Alexandra Amtul'],
          ['12', '1 4 1 Soham', '4 7 2 Rachana Soham', '7 8 4 Austin Collin Rachana Soham',
           '8 9 5 Austin Collin Rachana Sam Soham', '9 10 7 Austin Collin John Rachana Sam Soham Whitney',
           '10 11 8 Austin Collin John Rachana Sam Samuel Soham Whitney',
           '11 12 6 Collin John Kriti Sam Samuel Whitney',
           '12 13 5 Collin John Kriti Samuel Whitney', '13 16 6 Collin John Julie Kriti Samuel Whitney',
           '16 17 6 Collin Connie John Julie Samuel Whitney', '17 19 6 Collin John Julie Samuel Tanu Whitney',
           '19 21 2 Collin Samuel'], ['61', '1 2 3 Rahul Sumit Tejas', '2 3 4 Priya Rahul Sumit Tejas',
                                      '3 4 9 Angel Anushree Francisco Lisa Patrick Priya Rahul Sumit Tejas',
                                      '4 5 11 Angel Anushree Austin Daniel Francisco Lisa Patrick Priya Rahul Sumit Tejas',
                                      '5 6 14 Angel Anushree Austin Christopher Dana Daniel Lisa Miranda Patrick Priya Rahul Raju Sumit Tejas',
                                      '6 7 18 Angel Anushree Austin Christopher Colleen Dana Daniel Erica Lisa Michele Miranda Patrick Priya Rahul Raju Rohit Sumit Tejas',
                                      '7 8 17 Angel Anushree Austin Christopher Dana Daniel Erica Kristen Lisa Michele Miranda Priya Rahul Raju Rohit Sumit Tejas',
                                      '8 9 19 Angel Anushree Austin Christopher Dana Daniel Erica Kinjal Kristen Lauren Lisa Miranda Nikhil Priya Rahul Raju Rohit Sumit Tejas',
                                      '9 10 20 Angel Anushree Austin Christopher Dana Daniel Deanna Erica Kinjal Kristen Lauren Linda Miranda Nikhil Priya Rahul Rajni Raju Rohit Susan',
                                      '10 11 20 Angel Anushree Bryan Christopher Dana Daniel Deanna Erica James Kinjal Kristen Linda Miranda Nikhil Priya Rahul Rajni Raju Rohit Susan',
                                      '11 12 23 Angel Anushree Breanna Bryan Christopher Cody Dana Daniel Deanna James Kinjal Kristen Linda Miranda Nikhil Priya Rahul Rajas Rajni Raju Rohit Sarah Susan',
                                      '12 13 23 Angel Anushree Breanna Bryan Christopher Cody Dana Deanna James Kinjal Kristen Linda Meredith Miranda Nikhil Priya Rahul Rajas Rajni Raju Rohit Sarah Susan',
                                      '13 14 24 Angel Anushree Brad Breanna Bryan Christopher Cody Dana Deanna James Kinjal Kristen Linda Meredith Miranda Nikhil Priya Rahul Rajas Rajni Raju Rohit Sarah Susan',
                                      '14 15 19 Angel Anushree Brad Christopher Cody Dana Deanna James Jason Kristen Linda Miranda Nikhil Nishi Priya Rajas Raju Rohit Susan',
                                      '15 16 24 Angel Anubhav Anushree Brad Christopher Cody Dana Deanna Inder James Jason Kristen Linda Miranda Nikhil Nishi Priya Raj Rajas Raju Rohit Samantha Susan Tanya',
                                      '16 17 21 Andrea Angel Angela Anubhav Brad Christopher Cody Dana James Jason Kristen Linda Miranda Nikita Nishi Priya Raj Raju Rohit Samantha Tanya',
                                      '17 18 20 Andrea Angel Brad Christopher Cody James Jason Kristen Linda Mahesh Mary Miranda Neel Nikita Priya Raj Raju Rohit Samantha Tanya',
                                      '18 19 21 Ana Andrea Angel Christopher Cody Jason Kristen Linda Mahesh Mary Misty Neel Nikita Philip Pranav Priya Raj Rohit Tanya Tiffany Valerie',
                                      '19 20 21 Ana Andrea Angel Chandra Cody Girish Jason Julie Kristen Linda Mary Misty Neel Nikita Philip Pranav Priya Raj Tanya Tiffany Valerie',
                                      '20 21 16 Ana Angel Babita Chandra Girish Glenn Jason Julie Kristen Linda Mary Neel Pamela Philip Sejal Valerie']]
