az storage blob set-tier --account-key "acc_key"
                         --account-name "acc-name"
                         --container-name "cont_name"
                         --name "file_name"
                         --tier "Cool"
