- Hedge funds
  - Bridgewater Associates: One of the largest and most well-known hedge funds, known for its macro investing approach.
  - Renaissance Technologies: Known for its quantitative trading strategies and exceptional returns.
  - Two Sigma Investments: Uses technology and data science for investment strategies.
  - D.E. Shaw & Co.: Known for its focus on quantitative and systematic trading.
  - Millennium Management: A global investment management firm with a focus on alternative investment strategies.
  - Citadel: A global financial institution known for its hedge funds, asset management, and market-making activities.
  - Elliott Management Corporation: Known for its activist investing approach.
  - Brevan Howard: A global alternative asset manager focused on fixed income, currencies, and commodities.
  - Man Group: One of the world's largest publicly traded hedge fund companies.
  - AQR Capital Management: Known for its diversified approach to alternative investing. 
- Top proprietary trading firms
  - Jane Street Capital: Known for its quantitative trading strategies, particularly in the realm of high-frequency trading (HFT).
  - DRW: Known for its options market making and proprietary trading in various financial instruments.
  - Optiver: Specializes in market making and proprietary trading, particularly in options and futures.
  - Flow Traders: A leading global technology-enabled liquidity provider specializing in exchange traded products (ETPs).
  - IMC: Known for its market making and algorithmic trading in various asset classes.
  - SIG (Susquehanna International Group): Engaged in market making, proprietary trading, and investment activities.
  - Hudson River Trading: Focuses on algorithmic trading and market making in equities, futures, options, and currencies.
  - Tower Research Capital: Known for its quantitative trading strategies and algorithmic trading.  
