New-AZStorageAccount -Name "storage_acc_name"
                     -ResourceGroupName "rgroup"
                     -Location "westeurope"
                     -SkuName "Standard_RAGRS"
                     [optional->] -Kind "StorageV2"
